name: CI

on: 
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  test:
    # This ensures we run the test for only the PR or the push
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      matrix:
        version:
          - otp: 26.0
            elixir: 1.15.0
            os: ubuntu-latest
          - otp: 22.0
            elixir: 1.12.0
            # It's necessary to run on ubuntu 20.04 for OTP 20 - 23
            # See https://github.com/erlef/setup-beam
            os: ubuntu-20.04
    runs-on: ${{ matrix.version.os }}
    name: OTP ${{matrix.version.otp}} / Elixir ${{matrix.version.elixir}}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.version.otp}}
          elixir-version: ${{matrix.version.elixir}}
      - run: mix deps.get
      - run: mix test
      - run: MIX_ENV=test mix credo
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    name: Deploy published release
    env:
      HEX_API_KEY: ${{secrets.HEX_API_KEY}}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0
          elixir-version: 1.14
      - run: mix deps.get
      - run: mix hex.publish --yes